version: "3"
services:
  compute:
    image: 921992833788.dkr.ecr.us-west-2.amazonaws.com/compute:9.2.1
    ports:
      - "10000-10999:10000-10999"
      - "11000-11999:11000-11999"
      - "13400-13401:13400-13401"
      - "30000-30010:30000-30010"
      - "31531:31531"
      - "31538:31538"
      - "220:22"
      - "544:544"
    privileged: true
    hostname: is-compute-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /data0:/data0
    extra_hosts:
      - "is-en-conductor-0.en-cond:34.236.58.203"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "cloudoptim"
        awslogs-stream: "compute-1"
